version: '3.7'
services:
  mysql:
    image: mysql:8.0.19
    restart: on-failure
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=serialixample_dev
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=root
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './app/:/usr/src/app'
      - '/usr/src/app/var'
      - '/usr/src/app/vendor'
    environment:
      - DATABASE_URL=${DATABASE_URL:-mysql://db_user:db_password@mysql:3306/serialixample_dev?serverVersion=8.0.19}
    depends_on:
      - mysql
  nginx:
    image: nginx:1.17.8-alpine
    restart: on-failure
    volumes:
      - './app/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT:-8080}:80'
    depends_on:
      - php